services:
  timar:
    image: ghcr.io/shoshtari/timar
    pull_policy: always
    env_file: ./.env
    volumes:
      - sqlite_file:/etc/timar
    deploy:
      resources:
        limits:
          cpus: "0.2"

volumes:
  sqlite_file:
